FROM busybox:ubuntu-14.04

MAINTAINER Vincent Serpoul "<vincent@serpoul.com>"

WORKDIR /app

# copy binary into image
COPY playwithsqlcmd /app/

# Add influxd to the PATH
ENV PATH=/app:$PATH

ENTRYPOINT ["playwithsqlcmd", "-db=oracle", "-host=oracledb"]