FROM ubuntu:17.04

MAINTAINER Vincent Serpoul "<vincent@serpoul.com>"

COPY ./infra/oracle/instantclient-basiclite-linux.x64-12.2.0.1.0.zip /root/
COPY ./infra/oracle/instantclient-sdk-linux.x64-12.2.0.1.0.zip /root/
COPY ./infra/oracle/oci8.pc /root/

## ORACLE NEEDS
RUN apt-get clean && apt-get update && apt-get install -y --no-install-recommends \
        sqlite3 \
        gcc \
        alien \
        libaio1 \
        pkg-config \
        unzip && \
    rm -rf /var/lib/apt/lists/*
RUN mkdir -p /opt/oracle
WORKDIR /opt/oracle
RUN unzip /root/instantclient-basiclite-linux.x64-12.2.0.1.0.zip && \
    unzip /root/instantclient-sdk-linux.x64-12.2.0.1.0.zip

ENV LD_LIBRARY_PATH=/opt/oracle/instantclient_12_2:/opt/oracle/instantclient_12_2/sdk/include
ENV PKG_CONFIG_PATH=/opt/oracle
ENV PATH=/opt/oracle/instantclient_12_2:$PATH
ENV ORACLE_HOME=/opt/oracle/instantclient_12_2:/opt/oracle/instantclient_12_2/sdk/include

RUN ln -sf /opt/oracle/instantclient_12_2/libclntsh.so.12.1 /opt/oracle/instantclient_12_2/libclntsh.so && \
    ln -sf /opt/oracle/instantclient_12_2/libocci.so.12.1 /opt/oracle/instantclient_12_2/libocci.so

RUN cp -aL /root/oci8.pc $PKG_CONFIG_PATH/oci8.pc

WORKDIR /app

# copy binary into image
COPY playwithsql-cmd /app/

# Add influxd to the PATH
ENV PATH=/app:$PATH

ENTRYPOINT ["playwithsql-cmd"]