-- MySQL Script generated by MySQL Workbench
-- Thu 03 Nov 2016 10:41:45 PM SGT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `entityone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `entityone` (
  `entityone_id` BIGINT NOT NULL AUTO_INCREMENT,
  `time_created` DATETIME NOT NULL DEFAULT NOW(),
  PRIMARY KEY (`entityone_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `entityone_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `entityone_status` (
  `entityone_id` BIGINT NOT NULL,
  `action_id` BIGINT NOT NULL DEFAULT 1,
  `status_id` INT NOT NULL DEFAULT 1,
  `time_created` DATETIME NOT NULL DEFAULT NOW(),
  `is_latest` TINYINT(1) NULL DEFAULT 1 COMMENT 'can be null',
  UNIQUE INDEX `is_latest_UNIQUE` (`is_latest` ASC, `entityone_id` ASC),
  INDEX `index3` (`status_id` ASC, `is_latest` ASC),
  CONSTRAINT `fk_entityone_history_1`
    FOREIGN KEY (`entityone_id`)
    REFERENCES `entityone` (`entityone_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
